image: Visual Studio 2017
init:
 - git config --global core.autocrlf input

install:
  - echo %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - ps: choco install InnoSetup
  - appveyor DownloadFile https://github.com/winpython/winpython/releases/download/4.1.20210417/Winpython64-3.8.9.0dot.exe
  - dir
  - Winpython64-3.8.9.0dot.exe -y
  - dir
  - dir WPy64-3890
  - WPy64-3890\scripts\env.bat & WPy64-3890\python-3.8.9.amd64\Scripts\pip.exe install -r tools/module_reqs.txt
  # installing libtiff after we installed the requitements file as libtiff setup.py needs numpy which is installed by the prev command
  - WPy64-3890\scripts\env.bat & WPy64-3890\python-3.8.9.amd64\Scripts\pip.exe install libtiff

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd tools & call build.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd tools & call deploy.bat

artifacts:
  - path: tools\a3-dc-setup*.exe
